spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/satanaileoblog
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml



satanaileo:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
server:
  port: 8081

knife4j:
  enable: true
  openapi:
    title: blog文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: satanaileos@gmail.com
    concat: satanaileo
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.satanaileo.myblog.controller